backend:
  name: github
  repo: ivanmarribas/ivanmarribas.github.io
  branch: master # Branch to update (optional; defaults to master)

  media_folder: "src/assets" # Media files will be stored in the repo under images/uploads
  public_folder: "/assets" # The src attribute for uploaded media will begin with /images/uploads

  collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Articulos" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "TÃ­tulo", name: "title", widget: "string"}
      - {label: "Imagen destacada", name: "image", widget: "image"}
      - {label: "Categorias", name: "category", widget: "select", multiple: true, options: ["veganismo"]}
      - {label: "Contenido", name: "body", widget: "markdown"}
      - {label: "Fecha de publicacion", name: "date", widget: "datetime"}
      - {label: "Etiquetas", name: "tags", widget: "select", multiple: true, options: ["veganismo", "guerra"]}
      - { label: 'Autor', name: 'author', widget: 'hidden', default: "adrian" }